apiVersion: v1
kind: Service
metadata:
  name: logging-service
  namespace: oih-dev-ns
  labels:
    app: logging-service
spec:
  type: NodePort
  selector:
    app: logging-service
  ports:
  - name: "1234"
    protocol: TCP
    port: 1234
    targetPort: 1234
